language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

sudo: false

matrix:
  allow_failures:
    - php: hhvm
    - php: 7.0

env:
  - SYMFONY_VERSION=2.4.*
    COMPOSER_FLAGS="--prefer-lowest"
  - SYMFONY_VERSION=2.5.*
    COMPOSER_FLAGS="--prefer-lowest"
  - SYMFONY_VERSION=2.6.*
    COMPOSER_FLAGS="--prefer-lowest"
  - SYMFONY_VERSION=2.7.*
    COMPOSER_FLAGS=""

before_install:
  - composer self-update
  - composer require symfony/framework-bundle:${SYMFONY_VERSION} -n --prefer-source

install:
  - composer update  ${COMPOSER_FLAGS}

script:
  - ./bin/phpunit -v
  - ./bin/phpspec run -f pretty

notifications:
  irc: "irc.freenode.org#fsi-open"   
