language: php

cache:
    directories:
        - $HOME/.composer/cache
        - bin
        - vendor

sudo: false

matrix:
    include:
        - php: 7.1
          env:
            - COMPOSER_FLAGS='--prefer-lowest'
        - php: 7.1

before_install:
    - phpenv config-rm xdebug.ini
    - travis_wait 30 composer update $COMPOSER_FLAGS

script:
    - ./bin/phpunit -v
    - ./bin/phpspec run -f pretty
