language: php

cache:
    directories:
        - $HOME/.composer/cache

sudo: false

matrix:
    include:
        - php: 5.4
          env:
              - DEPENDENCIES='low'
        - php: 5.5
        - php: 5.6
        - php: 7.0

before_install:
    - composer self-update
    - if [[ "$DEPENDENCIES" != "low" && ! $SYMFONY_VERSION ]]; then composer update; fi;
    - if [[ "$DEPENDENCIES" == "low" ]]; then composer update --prefer-lowest; fi;

script:
  - ./bin/phpunit -v
  - ./bin/phpspec run -f pretty

notifications:
  irc: "irc.freenode.org#fsi-open"
