language: php

cache:
    directories:
        - $HOME/.composer/cache
        - bin
        - vendor

sudo: false

matrix:
    include:
        - php: 5.4
          env:
            - COMPOSER_FLAGS='--prefer-lowest'
        - php: 5.5
        - php: 5.6
        - php: 7.0
        - php: 7.1

before_install:
    - phpenv config-rm xdebug.ini || true
    - composer update $COMPOSER_FLAGS

script:
    - ./bin/phpunit -v
    - ./bin/phpspec run -f pretty

notifications:
  irc: "irc.freenode.org#fsi-open"
